name: timer
channels:
- bioconda
- hcc
- r
- quasiben
- ma-tongji
dependencies:
- libgcc=4.8.5=1
- libpng=1.6.17=0
- libtiff=4.0.6=1
- mysql=5.5.24=0
- numpy=1.10.4=py35_1
- pip=8.1.1=py35_1
- python=3.5.1=0
- r=3.2.2=0
- r-base=3.2.2=0
- setuptools=20.3=py35_0
- snakemake=3.6.1=py35_0
- sqlite=3.9.2=0
- zlib=1.2.8=0
- bioconductor-sva=3.18.0
- r-crayon=1.3.1
- r-sqldf

